#
# -*- coding: utf-8 -*-
#
# Copyright (C) 2025 Alexei Eskenazi. All rights reserved
#
# AI-Snap utility
#
# Author: amesk <alexei.eskenazi@gmail.com>
#

name: CI/CD Pipeline

on:
#  push:
#    branches:
#      - master
#      - releases/**
#  pull_request:
#    branches:
#      - master
#      - releases/**
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (build, publish-and-release)'
        required: true
        default: 'build'
        type: choice
        options:
          - build
          - publish-and-release

jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      ai_snap_version: ${{ steps.set-version.outputs.ai_snap_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set AI_SNAP_VERSION
        id: set-version
        run: |
          if [[ "${{ github.ref_name }}" == releases/* ]]; then
            VERSION_PARTS=(${GITHUB_REF_NAME#releases/})
            IFS='.' read -r -a VERSION_PARTS <<< "${VERSION_PARTS[0]}"
            MAJOR=${VERSION_PARTS[0]}
            MINOR=${VERSION_PARTS[1]}
            BUILD=${VERSION_PARTS[2]:-${{ github.run_number }}}
            AI_SNAP_VERSION="$MAJOR.$MINOR.$BUILD"
          else
            COMMIT_ID="${GITHUB_SHA:0:7}"
            AI_SNAP_VERSION="dev-$COMMIT_ID"
          fi
          echo "AI_SNAP_VERSION=$AI_SNAP_VERSION" >> $GITHUB_ENV
          echo "::set-output name=ai_snap_version::$AI_SNAP_VERSION"

  build:
    needs: set-version
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build the package (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pipenv run exe ${{ needs.set-version.outputs.ai_snap_version }}

      - name: Build the package (Linux)
        if: matrix.os != 'windows-latest'
        run: |
          pipenv run wheel ${{ needs.set-version.outputs.ai_snap_version }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.os }}
          path: dist/

  publish-and-release:
    needs:
      - set-version
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: >
      github.event_name == 'workflow_dispatch' &&
      github.event.inputs.action == 'publish-and-release'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Download artifacts for Linux
        uses: actions/download-artifact@v4
        with:
          name: package-ubuntu-latest
          path: dist/

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pipenv run twine upload dist/*.whl dist/*.tar.gz

      - name: Download artifacts for Windows
        uses: actions/download-artifact@v4
        with:
          name: package-windows-latest
          path: dist/

      - name: Create tag
        id: create-tag
        run: |
          if [[ "${{ github.ref_name }}" == releases/* ]]; then
            VERSION_PARTS=(${GITHUB_REF_NAME#releases/})
            IFS='.' read -r -a VERSION_PARTS <<< "${VERSION_PARTS[0]}"
            MAJOR=${VERSION_PARTS[0]}
            MINOR=${VERSION_PARTS[1]}
            BUILD=${VERSION_PARTS[2]:-${{ github.run_number }}}
            TAG_NAME="versions/$MAJOR.$MINOR.$BUILD"
            git tag $TAG_NAME
            git push origin $TAG_NAME
            echo "::set-output name=tag_name::$TAG_NAME"
          else
            echo "Not a release branch, skipping tag creation"
            exit 0
          fi

      - name: Generate Changelog
        run: |
          pipenv run changelog
          cat Changelog.txt

      - name: Create GitHub Release
        id: create-release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: ${{ steps.create-tag.outputs.tag_name }}
          name: Release ${{ steps.create-tag.outputs.tag_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          body_path: Changelog.txt
          files: |
            Changelog.txt
            dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
